#! /bin/sh

NAME=wireless

case "$1" in
	start)
		printf "Starting $NAME: "
		/volumio/app/plugins/system_controller/network/wireless.js start
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping $NAME: "
		/volumio/app/plugins/system_controller/network/wireless.js stop
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		echo "Restarting $NAME: "
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac

exit 0
