#! /bin/sh

NAME=iptables

case "$1" in
	start)
		printf "Starting $NAME: "
		/sbin/iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3000
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping $NAME: "
		start-stop-daemon -K -q -n $NAME
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		echo "Restarting $NAME: "
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac

exit 0
